### ISSUE TITLE
(URGENT) Mixed content at root not working

### ISSUE THREAD

**Issue by andrew2net** [lutaml/lutaml-model#57] opened 2024-08-21 20:05 UTC
I'm trying to use the mixed content option to parse the XML:
```xml
<docidentifier type="BIPM" scope="part" primary="true">CIPM 43<sup>e</sup> réunion (1950)</docidentifier>
```
The class:
```ruby
module Relaton
  module Model
    class Docidentifier < Lutaml::Model::Serializable

      attribute :type, Lutaml::Model::Type::String
      attribute :scope, Lutaml::Model::Type::String
      attribute :primary, Lutaml::Model::Type::Boolean
      attribute :sup, Lutaml::Model::Type::String

      xml do
        root "docidentifier", mixed: true
        map_element "sup", to: :sup
        map_attribute "type", to: :type
        map_attribute "scope", to: :scope
        map_attribute "primary", to: :primary
      end
    end
  end
end
```
The result:
```ruby
> docid = Relaton::Model::Docidentifier.from_xml xml
#class = Relaton::Model::Docidentifier
@element_order = ["text", :sup, "text"]
@ordered = true
@primary = true
@scope = "part"
@sup = "e"
@type = "BIPM"

> docid.to_xml
"<docidentifier type=\"BIPM\" scope=\"part\" primary=\"true\">\n" + "  <sup>e</sup>\n" + "</docidentifier>"
```
The text content disappears. What is wrong here?

**Comment by ronaldtse** [comment] 2024-08-22 00:18
Not sure what the error is but in the mixed content the elements like “sup” might be supposed to be “collection”.

**Comment by andrew2net** [comment] 2024-08-22 03:08
@ronaldtse Adding the `collection` option doesn't change anything. The [example](https://github.com/lutaml/lutaml-model#specifying-the-mixed-option-at-root) doesn't have the option too.

**Comment by ronaldtse** [comment] 2024-08-22 08:59
@andrew2net this will be handled by @HassanAkbar in #58 .

**Comment by HassanAkbar** [comment] 2024-09-03 08:05
@andrew2net the content is not mapped to anything that is why it is not showing in the output, for mapping content in xml we need to use the `map_content to: <attribute name>`.

So the above class will be changed to

```ruby
module Relaton
  module Model
    class Docidentifier < Lutaml::Model::Serializable

      attribute :type, Lutaml::Model::Type::String
      attribute :content, Lutaml::Model::Type::String
      attribute :scope, Lutaml::Model::Type::String
      attribute :primary, Lutaml::Model::Type::Boolean
      attribute :sup, Lutaml::Model::Type::String

      xml do
        root "docidentifier", mixed: true
        map_element "sup", to: :sup

        # for mapping content
        map_content to: :content

        map_attribute "type", to: :type
        map_attribute "scope", to: :scope
        map_attribute "primary", to: :primary
      end
    end
  end
end
```

**Comment by andrew2net** [comment] 2024-09-03 22:37
@HassanAkbar in the [doc](https://github.com/lutaml/lutaml-model#mixed-content) described same case without mapping content. Please update the doc.

It works, but I get another problem with [Separate serialization model](https://github.com/lutaml/lutaml-model#mixed-content)
```ruby
module Relaton
  module Bib
    class Docidentifier
      attr_accessor :type, :scope, :content
      ...

module Relaton
  module Model
    class Docidentifier < Lutaml::Model::Serializable
      model ::Relaton::Bib::Docidentifier
      ...
```
We need `Relaton::Bib::Docidentifier@content` to be set to `"CIPM 43<sup>e</sup> réunion (1950)"` when the `docidentifier` element is parsed
```ruby
xml = <<~XML
  <docidentifier language="en" script="Latn" locale="EN-us" type="BIPM" scope="part" primary="true">
    CIPM 43<sup>e</sup> réunion (1950)
  </docidentifier>
XML

docid = Relaton::Model::Docidentifier.from_xml xml
```
but the `Relaton::Model::Docidentifier` required to have `sup=` method in `Relaton::Bib::Docidentifier`. After adding the `sup` attribute I got:
```ruby
docid.content
=> ["\n" + "  CIPM 43", " r\u00E9union (1950)\n"]

docid.sup
=> ["e"]
```
Is there a way to solve this problem?

**Comment by ronaldtse** [comment] 2024-09-04 00:43
Looks like the `content` attribute needs to be specified as `mixed`? In general, we have not refined a good way of defining a mixed content model as easily done in RNC grammar. Something we need to work on.

**Comment by andrew2net** [comment] 2024-09-04 02:33
@ronaldtse mixed content also doesn't work.

I think we can make our life more easier using Nokogiri's feature that escapes all XML markups inside text nodes.
```ruby
id = Relaton::Bib::Docidentifier.new(type: "BIPM", content: "CIPM 43<sup>e</sup> réunion (1950)")

xml = Relaton::Model::Docidentifier.to_xml id
=> "<docidentifier type=\"BIPM\">CIPM 43&lt;sup&gt;e&lt;/sup&gt; r\u00E9union (1950)</docidentifier>"

id2 = Relaton::Model::Docidentifier.from_xml xml

puts id2.content
CIPM 43<sup>e</sup> réunion (1950)
```

**Comment by ronaldtse** [comment] 2024-09-04 04:48
@andrew2net Are you asking for an option to treat XML content as text?

What kind of API are you looking for the `Bib::Docidentifier` and `Model::Docidentifier` object?

Can you come up with some Ruby code showing what exactly you want to see?

**Comment by ronaldtse** [comment] 2024-09-10 00:18
@andrew2net so what should @HassanAkbar do here to fix the problem? I'm a bit confused.

So the problem is when using a separate model, the assigned `content` is no longer a string but is parsed like XML?

**Comment by andrew2net** [comment] 2024-09-10 04:43
@ronaldtse yes, content in the separated model should be
`CIPM 43<sup>e</sup> réunion (1950)`
but lutaml-model returns
`["\n" + "  CIPM 43", " r\u00E9union (1950)\n"]`

We can solve this issue by handling these IDs as String. In other words the ID in XML output will be escaped:
```xml
<docidentifier type="BIPM">CIPM 43&lt;sup&gt;e&lt;/sup&gt; r\u00E9union (1950)</docidentifier>
```
Nokogiri can encode and decode such content. I tested it and got desired content in separated model.

So we don't need to handle any tags in text element (there are a lot other tags for content defined in the grammar).

But the escaped tags aren't validated by Nokogiri. If that's ok then we can use this approach

**Comment by ronaldtse** [comment] 2024-09-11 04:45
@andrew2net Clearly we need to parse the content as a proper text model that checks its grammar/validity. Handling it as a string is a bad hack.

What is the text model there though?

Supposed it is a class called `RichText`, then we can just point `:content` to be casted as `RichText`?

**Comment by andrew2net** [comment] 2024-09-12 02:54
@ronaldtse docidentifier's [content](https://github.com/relaton/relaton-models/blob/2c42b172c341570545f7925702687c91e41c659e/grammars/biblio.rng#L1469) is [LocalizedMarkedUpString](https://github.com/relaton/relaton-models/blob/2c42b172c341570545f7925702687c91e41c659e/grammars/biblio.rng#L159) which is collection of [TextElement](https://github.com/metanorma/basicdoc-models/blob/79e0797fcf627e1f83678eb46ebf5252e54c41dc/grammars/basicdoc.rng#L1242)
If I tried to create `TextElement` but it doesn't returns string with tags
```ruby
class TextElement < Lutaml::Model::Serializable
  attribute :sup, :string
  attribute :sub, :string
  attribute :text, :string
  xml do
    root 'text-element', mixed: true
    map_content to: :text
    map_element "sup", to: :sup
    map_element "sub", to: :sub
  end
end

class Id
  attr_accessor :id
end

class Docid < Lutaml::Model::Serializable
  model Id
  attribute :id, TextElement
  xml do
    root 'docid'
    map_content to: :id
  end
end

> docid = Docid.from_xml '<docid>Str<sub>2</sub>text<sup>1</suo>123</docid>'
 => #<Id:0x000000012456c500 @id=["Str", "text", "123"]>

# it returns array of strings without tags
> docid.id
 => ["Str", "text", "123"]

# tags are lost
> Docid.to_xml docid
 => "<docid>Strtext123</docid>" 
```
What am I doing wrong?

**Comment by andrew2net** [comment] 2024-09-12 20:43
@HassanAkbar can you help with this issue?

**Comment by HassanAkbar** [comment] 2024-09-13 06:57
@andrew2net Sure, I'm looking into it right now

**Comment by HassanAkbar** [comment] 2024-09-13 07:12
@andrew2net To delegate the attributes to another model we need to use the `delegate` keyword.

```ruby
require "lutaml/model"
require "lutaml/model/xml_adapter/nokogiri_adapter"

Lutaml::Model::Config.xml_adapter = Lutaml::Model::XmlAdapter::NokogiriAdapter

class TextElement < Lutaml::Model::Serializable
  attribute :sup, :string
  attribute :sub, :string
  attribute :text, :string
  xml do
    root 'text-element', mixed: true
    map_content to: :text
    map_element "sup", to: :sup
    map_element "sub", to: :sub
  end
end

class Id
  attr_accessor :id
end

class Docid < Lutaml::Model::Serializable
  model Id
  attribute :id, TextElement
  xml do
    root 'docid'
    map_content to: :text, delegate: :id
    map_element :sub, to: :sub, delegate: :id
    map_element :sup, to: :sup, delegate: :id
  end
end

> docid = Docid.from_xml '<docid>Str<sub>2</sub>text<sup>1</suo>123</docid>'
 => #<Id:0x0000000108b253f0 @id=#<TextElement:0x0000000108b250f8 @sub="2", @sup="1", @text=["Str", "text", "123"], @validate_on_set=false>> 
```

But when we do something like `Docid.to_xml docid` it crashes because of the issue you mentioned here -> https://github.com/lutaml/lutaml-model/issues/83.

I'm currently working on it and will let you know as soon as it is resolved.

**Comment by andrew2net** [comment] 2024-09-13 18:46
@HassanAkbar it doesn't work:
```ruby
> docid = Docid.from_xml '<docid>Str<sub>2</sub>text<sup>1</suo>123</docid>'
gems/ruby-3.3.3/gems/lutaml-model-0.3.10/lib/lutaml/model/serialize.rb:317:in `block in apply_xml_mapping': Attribute 'sub' not found in Docid (RuntimeError)
```

**Comment by HassanAkbar** [comment] 2024-09-19 08:18
@andrew2net I have fixed the issue, it should work after https://github.com/lutaml/lutaml-model/pull/91 is merged.

**Comment by andrew2net** [comment] 2024-09-25 23:50
> ```ruby
> > docid = Docid.from_xml '<docid>Str<sub>2</sub>text<sup>1</suo>123</docid>'
>  => #<Id:0x0000000108b253f0 @id=#<TextElement:0x0000000108b250f8 @sub="2", @sup="1", @text=["Str", "text", "123"], @validate_on_set=false>> 
> ```

@HassanAkbar the `id` attribute is set to `TextElement` instance, but it needs to be `String`. In this case  `Str<sub>2</sub>text<sup>1</suo>123`. How can we achieve it?

**Comment by andrew2net** [comment] 2024-09-26 00:13
> ```ruby
>     map_element :sub, to: :sub, delegate: :id
>     map_element :sup, to: :sup, delegate: :id
> ```

@HassanAkbar `TextElement` has 22 elements. It is used as an attribute in dozens of other elements. Can we avoid repeating mapping elements every time we have `TextElement` attribute?
We have also similar `PureTextElement`, `NestedTextElement`, and other elements with mixed content. It will need to repeat thousands of lines of code.

**Comment by andrew2net** [comment] 2024-09-26 23:28
@HassanAkbar the `TextElement` has 20+ elements and is used in dozens cases as mixed content. This solution requires to delegate each `TextElement` element in each case where it is used:
> ```ruby
>     map_element :sub, to: :sub, delegate: :id
>     map_element :sup, to: :sup, delegate: :id
> ```
We also have `PureTextElement`, `NestedTextElement`, and some other, similar to `TextElement` elements. This requires writing thousands delegation lines of code. Can we avoid delegating each element of mixing content?

**Comment by ronaldtse** [comment] 2024-09-27 09:29
@andrew2net @HassanAkbar 

Why not just:
```
class TextElement < Lutaml::Model::Serializable
  attribute :sup, …
end

class Docid < Lutaml::Model::Serializable
  attribute :my_text_content, TextElement
end
```

**Comment by HassanAkbar** [comment] 2024-09-27 10:52
> @andrew2net @HassanAkbar
> 
> Why not just:
> 
> ```
> class TextElement < Lutaml::Model::Serializable
>   attribute :sup, …
> end
> 
> class Docid < Lutaml::Model::Serializable
>   attribute :my_text_content, TextElement
> end
> ```


@ronaldtse  the issue with this is that in xml we have different mappings for `attributes`, `elements` and `content`. So currently we can not decide about which of the above we need to send to the `my_text_content`.

I think what we can do here is, make another tag like `map_raw_content` or `map_all` or simply `map` to map the entire tag's content as string to the attribute. What do you suggest?

**Comment by ronaldtse** [comment] 2024-09-27 12:30
> the issue with this is that in xml we have different mappings for `attributes`, `elements` and `content`. So currently we can not decide about which of the above we need to send to the `my_text_content`.

I don't really understand this. Can you provide an example XML with a Lutaml::Model code snippet to illustrate?

**Comment by HassanAkbar** [comment] 2024-09-27 12:51
> > the issue with this is that in xml we have different mappings for attributes, elements and content. So currently we can not decide about which of the above we need to send to the my_text_content.
>
> I don't really understand this. Can you provide an example XML with a Lutaml::Model code snippet to illustrate?

```ruby
class TextElement < Lutaml::Model::Serializable
  attribute :sup, …
end

class Docid < Lutaml::Model::Serializable
  attribute :my_text_content, TextElement
end
```

```xml
<docid>
  Str <sub>2</sub> text <sup>1</suo> 123
</docid>
```

@ronaldtse In this example above the xml for `docid` has 
- content -> text = ["Str", "text", "123"]
- element -> sub = 2
- element -> sup = 1

and we need to define the mappings for all `elements`, `attributes` and `content` in the `docid` to map them to the proper attributes. 
From what I understand from the @andrew2net example is that this needs to happen for lots of elements that have lots of tags and mapping all those tags has no benefit so mapping them to a string is sufficient.

So, what I'm proposing is adding a tag like `map_all to: :raw_text` which will map all the content inside the tag to that attribute. e.g

```ruby
class Docid < Lutaml::Model::Serializable
  attribute :my_text_content, :string

  xml do
    map_all to: : my_text_content
  end
end

docid = Docid.from_xml '<docid>Str<sub>2</sub>text<sup>1</suo>123</docid>'
# <Docid:0x0000000108b253f0 @my_text_content="Str<sub>2</sub>text<sup>1</suo>123", @validate_on_set=false> 
```

we can rename `map_all` to something more fitting but this is a rough idea I have in mind for this.

**Comment by andrew2net** [comment] 2024-09-28 02:04
@HassanAkbar the last example looks good to me

**Comment by ronaldtse** [comment] 2024-10-18 18:02
@HassanAkbar Got it, then let's move ahead with `map_all`. We also need to ensure that the other `map_*` methods can't be used together with `map_all`.

**Comment by HassanAkbar** [comment] 2024-10-21 06:19
> We also need to ensure that the other map_* methods can't be used together with map_all.

@ronaldtse Got it, will add a validation for that

**Closed** 2024-11-01 05:33 UTC
Labels: bug
